import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%FABRICA_AGENT_HOOK_PORT%"=="" if defined FABRICA_AGENT_HOOK_ENDPOINT if exist "%FABRICA_AGENT_HOOK_ENDPOINT%" call "%FABRICA_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%FABRICA_AGENT_HOOK_TOKEN%"=="" if not "%FABRICA_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\fabrica-dev\\agent-hooks" for /r "%APPDATA%\\fabrica-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%FABRICA_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\Fabrica\\agent-hooks" for /r "%APPDATA%\\Fabrica\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%FABRICA_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set FABRICA_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%FABRICA_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    '__FABRICA_read_ancestor_var() {',
    '  __FABRICA_name="$1"',
    '  __FABRICA_pid="${PPID:-}"',
    '  while [ -n "$__FABRICA_pid" ] && [ "$__FABRICA_pid" != "0" ] && [ "$__FABRICA_pid" != "1" ]; do',
    '    __FABRICA_value=""',
    '    if [ -r "/proc/$__FABRICA_pid/environ" ]; then',
    '      __FABRICA_value=$(tr "\\000" "\\n" < "/proc/$__FABRICA_pid/environ" 2>/dev/null | sed -n "s/^${__FABRICA_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__FABRICA_value" ]; then',
    '      __FABRICA_value=$(ps eww -p "$__FABRICA_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__FABRICA_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__FABRICA_value" ]; then',
    '      printf "%s\\n" "$__FABRICA_value"',
    '      return 0',
    '    fi',
    '    __FABRICA_pid=$(ps -o ppid= -p "$__FABRICA_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__FABRICA_fill_from_ancestor() {',
    '  __FABRICA_name="$1"',
    '  case "$__FABRICA_name" in',
    '    FABRICA_AGENT_HOOK_ENDPOINT) [ -z "${FABRICA_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    FABRICA_AGENT_HOOK_PORT) [ -z "${FABRICA_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    FABRICA_AGENT_HOOK_TOKEN) [ -z "${FABRICA_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    FABRICA_AGENT_HOOK_ENV) [ -z "${FABRICA_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    FABRICA_AGENT_HOOK_VERSION) [ -z "${FABRICA_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    FABRICA_PANE_KEY) [ -z "${FABRICA_PANE_KEY:-}" ] || return 0 ;;',
    '    FABRICA_TAB_ID) [ -z "${FABRICA_TAB_ID:-}" ] || return 0 ;;',
    '    FABRICA_WORKTREE_ID) [ -z "${FABRICA_WORKTREE_ID:-}" ] || return 0 ;;',
    '    FABRICA_AGENT_LAUNCH_TOKEN) [ -z "${FABRICA_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __FABRICA_value=$(__FABRICA_read_ancestor_var "$__FABRICA_name") || return 0',
    '  [ -n "$__FABRICA_value" ] && export "$__FABRICA_name=$__FABRICA_value"',
    '}',
    '__FABRICA_endpoint_value() {',
    '  __FABRICA_endpoint_name="$1"',
    '  __FABRICA_endpoint_path="$2"',
    '  sed -n "s/^${__FABRICA_endpoint_name}=//p" "$__FABRICA_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__FABRICA_fill_from_endpoint_file() {',
    '  __FABRICA_endpoint_path="$1"',
    '  [ -r "$__FABRICA_endpoint_path" ] || return 0',
    '  __FABRICA_endpoint_port=$(__FABRICA_endpoint_value FABRICA_AGENT_HOOK_PORT "$__FABRICA_endpoint_path")',
    '  if [ -n "${FABRICA_AGENT_HOOK_PORT:-}" ] && [ -n "$__FABRICA_endpoint_port" ] && [ "$__FABRICA_endpoint_port" != "$FABRICA_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __FABRICA_endpoint_name in FABRICA_AGENT_HOOK_PORT FABRICA_AGENT_HOOK_TOKEN FABRICA_AGENT_HOOK_ENV FABRICA_AGENT_HOOK_VERSION; do',
    '    eval "__FABRICA_current=\\${$__FABRICA_endpoint_name:-}"',
    '    [ -z "$__FABRICA_current" ] || continue',
    '    __FABRICA_endpoint_value=$(__FABRICA_endpoint_value "$__FABRICA_endpoint_name" "$__FABRICA_endpoint_path")',
    '    [ -n "$__FABRICA_endpoint_value" ] && export "$__FABRICA_endpoint_name=$__FABRICA_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has FABRICA pane/hook metadata, so recover it before posting.',
    'for __FABRICA_name in FABRICA_AGENT_HOOK_ENDPOINT FABRICA_AGENT_HOOK_PORT FABRICA_AGENT_HOOK_TOKEN FABRICA_AGENT_HOOK_ENV FABRICA_AGENT_HOOK_VERSION FABRICA_PANE_KEY FABRICA_TAB_ID FABRICA_WORKTREE_ID FABRICA_AGENT_LAUNCH_TOKEN; do',
    '  __FABRICA_fill_from_ancestor "$__FABRICA_name"',
    'done',
    'if [ -n "$FABRICA_AGENT_HOOK_ENDPOINT" ] && [ -r "$FABRICA_AGENT_HOOK_ENDPOINT" ]; then',
    '  __FABRICA_fill_from_endpoint_file "$FABRICA_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# FABRICA_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$FABRICA_AGENT_HOOK_TOKEN" ] && [ -n "$FABRICA_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/fabrica-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/fabrica-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/fabrica-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/fabrica-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/Fabrica/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/Fabrica/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^FABRICA_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$FABRICA_AGENT_HOOK_PORT" ]; then',
    '      __FABRICA_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$FABRICA_AGENT_HOOK_PORT" ] || [ -z "$FABRICA_AGENT_HOOK_TOKEN" ] || [ -z "$FABRICA_PANE_KEY" ]; then',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${FABRICA_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-FABRICA-Agent-Hook-Token: ${FABRICA_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${FABRICA_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${FABRICA_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${FABRICA_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${FABRICA_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${FABRICA_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${FABRICA_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || true',
    'exit 0',
    ''
  ].join('\n')
}
